name: Deploy to StreamingCuba VPS
 
on:
  push:
    # tags:
    #   - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Send Telegram notification
#       uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.PERSONAL_TELEGRAM_USER_ID }}
#          token: ${{ secrets.NOTIFICATIONS_TELEGRAM_BOT_TOKEN }}
#          args: The ${{ github.event_name }} event triggered the "Deploy to StreamingCuba VPS" workflow.


      - name: Post deploy SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:        
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 60s
          debug: true
          script: sudo sh /home/streaming/apps/events-backend/deploy.sh


