name: Deploy to QA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Replace secrets
      #   run: |
      #    sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.QA_DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.QA_DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.QA_DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_USER/${{ secrets.QA_DATABASE_USER }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_PASSWORD/${{ secrets.QA_DATABASE_PASSWORD }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_HOST/${{ secrets.QA_DATABASE_HOST }}/g' Events.API/appsettings.json
      #    sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json
      #    sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_EVENTS_NAME secret
        run: sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.QA_DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_ACCOUNTS_NAME secret
        run: sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.QA_DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_SUBSCRIBERS_NAME secret
        run: sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.QA_DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_USER secret
        run: sed -i 's/DATABASE_USER/${{ secrets.QA_DATABASE_USER }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_PASSWORD secret
        run: sed -i 's/DATABASE_PASSWORD/${{ secrets.QA_DATABASE_PASSWORD }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_HOST secret
        run: sed -i 's/DATABASE_HOST/${{ secrets.QA_DATABASE_HOST }}/g' Events.API/appsettings.json

      - name: Replace DATABASE_PORT secret
        run: sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json

      - name: Replace JWT_KEY secret
        run: sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
