name: Deploy to Production
 
on:
  push:
   tags:
    - "v*"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace secrets
        run: |
         sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_USER/${{ secrets.DATABASE_USER }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PASSWORD/${{ secrets.DATABASE_PASSWORD }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_HOST/${{ secrets.DATABASE_HOST }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json
         sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json
         sed -i 's/MEDIA_PATH/${{ secrets.MEDIA_PATH }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_TOKEN/${{ secrets.FACEBOOK_TOKEN }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_PAGE_IDENTIFIER/${{ secrets.FACEBOOK_PAGE_IDENTIFIER }}/g' Events.API/appsettings.json
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.113
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish release
        run: dotnet publish -c Release      

      - name: Copying publish assets
        uses: garygrossgarten/github-action-scp@release
        with:
          local: Events.API/bin
          remote: /home/streaming/apps/events-backend/Events.API/bin
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rmRemote: true
          atomicPut: true
          dotfiles: true
          verbose: true

      - name: Post deploy SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:        
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 60s
          debug: true
          script: sudo sh /home/streaming/apps/events-backend/deploy.sh