name: Deploy to QA

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace secrets
        run: |
         sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.QA_DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.QA_DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.QA_DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_USER/${{ secrets.QA_DATABASE_USER }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PASSWORD/${{ secrets.QA_DATABASE_PASSWORD }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_HOST/${{ secrets.QA_DATABASE_HOST }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json
         sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json
         sed -i 's/MEDIA_PATH/${{ secrets.QA_MEDIA_PATH }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_TOKEN/${{ secrets.FACEBOOK_TOKEN }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_PAGE_IDENTIFIER/${{ secrets.FACEBOOK_PAGE_IDENTIFIER }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_HOST/${{ secrets.EMAIL_HOST }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_PORT/${{ secrets.EMAIL_PORT }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_SENDER_ADDRESS/${{ secrets.EMAIL_SENDER_ADDRESS }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_SENDER_DISPLAY_NAME/${{ secrets.EMAIL_SENDER_DISPLAY_NAME }}/g' Events.API/appsettings.json
         sed -i 's/RECAPTCHA_SECRET_KEY/${{ secrets.RECAPTCHA_SECRET_KEY }}/g' Events.API/appsettings.json
         sed -i 's/RECAPTCHA_SITE_KEY/${{ secrets.RECAPTCHA_SITE_KEY }}/g' Events.API/appsettings.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.113     

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Installing Entity Framework Tools
        run: dotnet tool install --global dotnet-ef
        
      - name: Updating Databases
        run: |
          dotnet ef database update --context EventContext --project ./Events.API   
          dotnet ef database update --context AccountContext --project ./Events.API  
          dotnet ef database update --context SubscriberContext --project ./Events.API 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace secrets
        run: |
         sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.QA_DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.QA_DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.QA_DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_USER/${{ secrets.QA_DATABASE_USER }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PASSWORD/${{ secrets.QA_DATABASE_PASSWORD }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_HOST/${{ secrets.QA_DATABASE_HOST }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json
         sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json
         sed -i 's/MEDIA_PATH/${{ secrets.QA_MEDIA_PATH }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_TOKEN/${{ secrets.FACEBOOK_TOKEN }}/g' Events.API/appsettings.json
         sed -i 's/FACEBOOK_PAGE_IDENTIFIER/${{ secrets.FACEBOOK_PAGE_IDENTIFIER }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_HOST/${{ secrets.EMAIL_HOST }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_PORT/${{ secrets.EMAIL_PORT }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_SENDER_ADDRESS/${{ secrets.EMAIL_SENDER_ADDRESS }}/g' Events.API/appsettings.json
         sed -i 's/EMAIL_SENDER_DISPLAY_NAME/${{ secrets.EMAIL_SENDER_DISPLAY_NAME }}/g' Events.API/appsettings.json
         sed -i 's/RECAPTCHA_SECRET_KEY/${{ secrets.RECAPTCHA_SECRET_KEY }}/g' Events.API/appsettings.json
         sed -i 's/RECAPTCHA_SITE_KEY/${{ secrets.RECAPTCHA_SITE_KEY }}/g' Events.API/appsettings.json

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
