name: Update QA databases

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Replace secrets
        run: |
         sed -i 's/DATABASE_EVENTS_NAME/${{ secrets.QA_DATABASE_EVENTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_ACCOUNTS_NAME/${{ secrets.QA_DATABASE_ACCOUNTS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_SUBSCRIBERS_NAME/${{ secrets.QA_DATABASE_SUBSCRIBERS_NAME }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_USER/${{ secrets.QA_DATABASE_USER }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PASSWORD/${{ secrets.QA_DATABASE_PASSWORD }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_HOST/${{ secrets.QA_DATABASE_HOST }}/g' Events.API/appsettings.json
         sed -i 's/DATABASE_PORT/${{ secrets.DATABASE_PORT }}/g' Events.API/appsettings.json
         sed -i 's/JWT_KEY/${{ secrets.JWT_KEY }}/g' Events.API/appsettings.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.113
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Installing Entity Framework Tools
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore

    - name: Updating Events Database
      run: dotnet ef database update --context EventContext --project ./Events.API
    
    - name: Updating Accounts Database
      run: dotnet ef database update --context AccountContext --project ./Events.API

    - name: Updating Subscribers Database
      run: dotnet ef database update --context SubscriberContext --project ./Events.API
